# HolyAnnouncer Configuration File

# How to use MiniMessage:
# https://docs.advntr.dev/minimessage/format.html

# MiniMessage Playground;
# https://webui.advntr.dev/

# How many minutes to wait before sending announcement
announce_time_minutes: 15

# Use /ah reload to reload config
announce_message:
  - "<dark_gray>»-----------------------"
  - "<color:#F0C800><bold>       Holy Hosting"
  - ""
  - "<bold>Este servidor está patrocinado"
  - "<white>por <color:#F0C800><bold>Holy Hosting"
  - ""
  - "<gold>Consigue tu servidor en"
  - "<gold><bold><click:open_url:'https://holy.gg/minecraft'>holy.gg/minecraft [Click Aqui]</click>"
  - "<dark_gray>»-----------------------"
