# HolyAnnouncer Configuration File

# How to use MiniMessage:
# https://docs.advntr.dev/minimessage/format.html

# MiniMessage Playground;
# https://webui.advntr.dev/


# How many minutes to wait before sending announcement
announce_time_minutes: 15

# Use /ah reload to reload config
announce_message:
  - "<dark_gray>»-------------------"
  - "<white>Holy Hosting"
  - ""
  - "<wihte>Este servidor está patrocinado"
  - "<white>por Holy Hosting"
  - "<gold>Consigue tu servidor en"
  - "<white>holy.gg"
  - "<dark_gray>»-------------------"
