# HolyAnnouncer Configuration File

# How to use MiniMessage:
# https://docs.advntr.dev/minimessage/format.html

# MiniMessage Playground;
# https://webui.advntr.dev/

# How many minutes to wait before sending announcement
announce_time_minutes: 15

# Use /ah reload to reload config
announce_message:
  - "<dark_gray>»-------------------"
  - "<white>Holy Hosting"
  - ""
  - "<wihte>Este servidor está patrocinado"
  - "<white>por Holy Hosting"
  - "<gold>Consigue tu servidor en"
  - "<red><bold><click:open_url:'https://www.holy.gg/minecraft'>holy.gg [Click Aqui]</click>"
  - "<dark_gray>»-------------------"

# Uncomment to use custom messages
#announce_message:
#  - "&8»-------------------"
#  - "       Holy Hosting"
#  - ""
#  - "&lEste servidor está patrocinado"
#  - "&fpor &e&lHoly Hosting"
#  - "&eConsigue tu servidor en"
#  - "&e&lholy.gg"
#  - "&8»-------------------"